repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args:
          [--exclude, tests, --exclude, tcex/testing, tcex/app_config_object/*]
        exclude: ^lib,tcex/testing,app_init
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.1.3
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        args:
          - --ignore=D104,D202,D203,D213,D301,D400,D406,D407,D413,D415
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.1
    hooks:
      - id: pyupgrade
        exclude: ^lib
  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        args: ["--max-average=A", "--max-modules=B", "--max-absolute=B"]
  - repo: local
    hooks:
      - id: pylint
        args:
          # C0103 - invalid-name
          # C0302 - too-many-lines
          # C0330 - bad-continuation
          # C0401 - wrong-spelling
          # R0205 - useless-object-inheritance
          # R0801 - duplicate-code
          # R0902 - too-many-instance-attributes
          # R0903 - too-few-public-methods
          # R0904 - too-many-public-methods
          # R0912 - too-many-branches
          # R0913 - too-many-arguments
          # R0914 - too-many-locals
          # R0915 - too-many-statements
          # R1702 - too-many-nested-blocks
          # W0212 - protected-access
          # W0511 - fixme
          # W0703 - broad-except
          # W1203 - logging-fstring-interpolation
          - --disable=C0103,C0302,C0330,C0415,E0401,R0205,R0801,R0902,R0903,R0904,R0912,R0913,R0914,R0915,R1702,W0212,W0511,W0703,W1203
          - --ignore-patterns=app_init*
        entry: pylint
        language: system
        name: pylint
        types: [python]
